Cascade delete on route and pattern delete
conveyal/gtfs-lib pull request #350
Opened 2022-04-25 14:57 UTC by br648

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

To address these Jira tickets:

1. https://ibisolutions.atlassian.net/browse/DT-71
2. https://ibisolutions.atlassian.net/browse/DT-72 

A refactor to delete pattern stops, stop times, frequencies and shapes when a route or pattern is deleted. DT only has one level deep deletes, so prior to this update only patterns and trips were deleted leaving orphaned pattern stops, stop times, frequencies and shapes (second level references).

To test locally run the following maven command on GTFS-Lib: `mvn install -Dmaven.test.skip=true` and then update the datatools-server dependency to:

```
        <dependency>
            <groupId>com.conveyal</groupId>
            <artifactId>gtfs-lib</artifactId>
            <version>7.0.2</version>
            
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

```
### NOTE!

It looks like this will require an update to the UI as well in the form of a refresh. With an update in place to delete shapes if a route or pattern is deleted the route alignments remain until the map is refreshed. E.g. Click on “Back to Feed” and then “Edit feed” will show the updated route alignments.

2022-04-28 16:23 UTC, binh-dam-ibigroup requested changes
Seems to work! I would rename some vars as indicated. And can we replace prepared statements with just straight statements since they are not reused?

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +     * @throws SQLException TODO? add param Set<String> serviceIdFilters service_id values to filter trips on
Revert placing TODO on same line as `@throws`.

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +                        table.name.equals(Table.ROUTES.name)
These two `if` conditions are difficult to follow, so could you add comments to explain what each check in each `if` block means?

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +    private void deleteStopTimesAndFrequencies(String namespace, String keyValue, String keyColumn, String specTable)
To give it more context, I would rename `keyValue` to `routeOrPatternId`, and `keyColumn` to `routeOrPatternIdColumn`.

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +        int deletedStopTimes = executePreparedStatement(
Is a prepared statement needed in this instance and the one below, since the statement is not reused (all params are passed at once)?

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +    private void deleteShapes(String namespace, String keyValue, String keyColumn, String specTable)
To give it more context, I would rename `keyValue` to `routeOrPatternId`, and `keyColumn` to `routeOrPatternIdColumn`.

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +    private void deleteStopTimesAndFrequencies(String namespace, String keyValue, String keyColumn, String specTable)
`specTable` is the referencing table or origin table, isn't it? Maybe it could be renamed to `referencingTable` too.

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +    private void deleteShapes(String namespace, String keyValue, String keyColumn, String specTable)
`specTable` is the referencing table or origin table, isn't it? Maybe it could be renamed to `referencingTable` too.

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +        int deletedShapes = executePreparedStatement(deleteShapes, keyValue);
Is a prepared statement needed here? (All params are passed at once.)

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +    private void deletePatternStops(String namespace, String keyValue) throws SQLException {
Rename `keyValue` to `routeId` to give more context.

2022-04-28 16:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +                        deleteShapes(namespace, keyValue, keyColumn, table.name);
I think you can get rid of the `namespace` variable, there is a field `tablePrefix` that carries the namespace (it's actually `<namespace>.` IIRC)

2022-04-29 09:34 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +                        table.name.equals(Table.ROUTES.name)
Refactored, it's much cleaner now.

2022-04-29 10:32 UTC, br648 commented
@binh-dam-ibigroup feedback addressed, thanks. I've also refactored which has cleaned this up a bit.

2022-04-29 13:03 UTC, binh-dam-ibigroup approved these changes
LGTM, thanks for the changes!

2022-04-29 13:03 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +    private void deleteDescendants(String parentTableName, String keyValue) throws SQLException {
Rename `keyValue` to `routeOrPatternId` for more context.

2022-04-29 13:03 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +        if (
Yep this is a better spot for this code.

2022-05-03 20:58 UTC, philip-cline approved these changes
Nit picky and maybe it's not worth it, but should we add a test deleting frequencies too?

2022-05-04 07:57 UTC, br648 commented
@philip-cline Updated to test deleting frequencies.

2022-05-04 08:46 UTC, merged