Add primary key names to Table class
conveyal/gtfs-lib pull request #379
Opened 2023-05-10 20:10 UTC by philip-cline

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing
- [ ] The description lists all relevant PRs included in this release _(remove this if not merging to master)_
- [ ] Code coverage does not significantly worsen (ideally it improves) _(remove this if not merging to master)_

### Description

This PR provides the ability to add primary key names for each table in the Table class, which are used by the new transformation to preserve custom fields (https://github.com/ibi-group/datatools-ui/pull/950 and https://github.com/ibi-group/datatools-server/pull/536).

2023-05-11 10:30 UTC, br648 requested changes
Just a few minor items to address.

2023-05-11 10:30 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> +        List<String> keys = new ArrayList<>();
Can be shortened to: `return Arrays.asList(primaryKeyNames);`

2023-05-11 10:30 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> -            .hasCompoundKey();
Did you mean to remove this line? I would add it back in.

2023-05-11 10:30 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> +     * Get field names that are primary keys for a table.
Perhap add here where this is used. Because it isn't used within GTFS-lib the method is flagged as "never used" which is miss leading.

2023-05-15 14:42 UTC, philip-cline commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> +        List<String> keys = new ArrayList<>();
Good call! Changed that in https://github.com/conveyal/gtfs-lib/pull/379/commits/031872599d41fbafd026dec175d5292fbe7b2301

2023-05-15 14:42 UTC, philip-cline commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> -            .hasCompoundKey();
Good catch, I put this back in https://github.com/conveyal/gtfs-lib/pull/379/commits/031872599d41fbafd026dec175d5292fbe7b2301

2023-05-15 14:43 UTC, philip-cline commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> +     * Get field names that are primary keys for a table.
I added a comment in https://github.com/conveyal/gtfs-lib/pull/379/commits/031872599d41fbafd026dec175d5292fbe7b2301 although it does seem a bit awkward to reference another repo here

2023-05-15 15:30 UTC, br648 approved these changes
LGTM

2023-05-15 15:31 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> +     * Get field names that are primary keys for a table.
@philip-cline , you do have a point. Perhaps one for the tech call?

2023-05-16 12:18 UTC, miles-grant-ibigroup approved these changes
Looks good! I love how clean this is. 

Just one nitpick: could you possibly always put the `addPrimaryKeyNames` on a new line?

2023-05-16 12:18 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> +    public Table addPrimaryKeyNames(String ...keys) {
This is very clever!

2023-05-16 14:22 UTC, merged