Add gitter to readme
conveyal/gtfs-lib pull request #382
Opened 2023-05-16 20:47 UTC by philip-cline

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Adds link to Gitter room dedicated to GTFS-lib discussion. Slightly awkward since this is under the TRANSIT-data-tools space but since the TRANSIT-data-tools team is the main maintainer of this repo right now, this seems ok.

2023-05-17 13:52 UTC, miles-grant-ibigroup requested changes
Is it possible to swap out the links for the `Gitter.im` ones?

2023-06-15 18:12 UTC, philip-cline commented
The gitter ones were not working, I have moved this to matrix links which should work.

2023-06-16 14:11 UTC, miles-grant-ibigroup approved these changes
New link not working for me either

2023-08-10 14:00 UTC, binh-dam-ibigroup approved these changes
One tiny change but otherwise good to go.

2023-08-10 14:00 UTC, binh-dam-ibigroup commented on README.md
> +We have a Gitter [space](https://matrix.to/#/#transit-data-tools:gitter.im) for the full TRANSIT-Data-Tools project where you can post questions and comments. This includes a room dedicated to GTFS-l
```suggestion
We have a [Gitter space](https://matrix.to/#/#transit-data-tools:gitter.im) for the full TRANSIT-Data-Tools project where you can post questions and comments. This includes a room dedicated to GTFS-lib discussions.
```

2023-08-10 14:10 UTC, merged