Exception based scheduling
conveyal/gtfs-lib pull request #385
Opened 2023-06-22 09:22 UTC by br648

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

TDC.

2023-07-25 20:54 UTC, binh-dam-ibigroup reviewed
Need to play with this code more, but see my comments so far.

2023-07-25 20:54 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java
>                              .collect(Collectors.toList())
Replace `for... collect(...)` with just `.forEach`?

2023-07-25 20:54 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java
> +                    calendarDateCount++;
Are we expecting errors? Otherwise, `calendarDateCount` should be the same as `calendarDateExceptions.size()`.

2023-07-25 20:54 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java
> +                    String serviceId = entry.getValue();
Extract a method for the similar content of this for loop and the one above at line 287.

2023-07-25 20:54 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +
Not needed.

2023-07-25 20:54 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java
> +            }
Extract method (move comments at lines 85-87 into method), inline result into if condition at line 97, delete comment at line 98.

2023-07-25 20:54 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java
> +                            dummyCalendarsByServiceId.put(calendarDate.service_id, calendar);
Probably extract a method.

2023-07-25 20:54 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java
> +                }
Extract method that is common with code from `JdbcGtfsExporter`, lines 133-140?

2023-07-26 15:17 UTC, binh-dam-ibigroup approved these changes
I'm able to replicate a correct export of a schedule exception not linked to a calendar (with some cheating), so I will go ahead and approve subject to the refactorings I mentioned in my previous comment.

2023-08-08 08:48 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java
>                              .collect(Collectors.toList())
"Variable used in lambda expression should be final or effectively final". So leaving as is.

2023-08-23 20:53 UTC, philip-cline requested changes
Code looks good, but right now I'm a bit confused about the use of the `ScheduleException` name as the service_id for a calendar_date based service. For example, calendar_dates may be used to add service on 2023-05-29 and 2023-07-04 for a service ID "4" which does not exist in calendar.txt. These would be represented as two separate calendar_dates but right now result in two separate ScheduleExceptions but with the same `name`. How should this use case be handled if we requiring name to be unique?
![image](https://github.com/conveyal/gtfs-lib/assets/63798641/af0cd10f-92d6-45ef-8a72-2b6646902632)

2023-08-23 20:53 UTC, philip-cline commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java
> +                // Extract calendar date services, convert to calendar date and add to the feed. We are expect only one
```suggestion
                // Extract calendar date services, convert to calendar date and add to the feed. We are expecting only one
```

2023-08-23 20:53 UTC, philip-cline commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +                                    LOG.info("{} reference(s) in {} {}D!", result, refTableName, sqlMethod);
Is the `D` intentional? 
```suggestion
                                    LOG.info("{} reference(s) in {} {}!", result, refTableName, sqlMethod);
```

2023-08-24 07:25 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
> +                                    LOG.info("{} reference(s) in {} {}D!", result, refTableName, sqlMethod);
Yep! The SQL method is either UPDATE or DELETE and the 'D' makes it past tense.

2023-08-29 10:54 UTC, br648 commented
> Code looks good, but right now I'm a bit confused about the use of the `ScheduleException` name as the service_id for a calendar_date based service. For example, calendar_dates may be used to add service on 2023-05-29 and 2023-07-04 for a service ID "4" which does not exist in calendar.txt. These would be represented as two separate calendar_dates but right now result in two separate ScheduleExceptions but with the same `name`. How should this use case be handled if we requiring name to be unique? ![image](https://user-images.githubusercontent.com/63798641/262796036-af0cd10f-92d6-45ef-8a72-2b6646902632.png)

@philip-cline How does this look? If the calendar date is not assoicated with a calendar the name is made up of service id and the first date. For `only-in-calendar-dates-txt-20170916` there is only one entry so strictly speaking the appended date is not needed, but for consistency I've kept it.

![image](https://github.com/conveyal/gtfs-lib/assets/28602741/8df54c7a-fed0-4015-a8cf-cfb85ba37c3e)

2023-08-29 14:16 UTC, philip-cline commented
Thanks yeah this is looking good. I'll start on a front end PR for this.

2023-11-14 14:30 UTC, philip-cline approved these changes
LGTM to me now

2023-11-14 14:32 UTC, merged